#!/usr/bin/env python3
"""
visualize_training_logs.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Visualize training loss and/or accuracy curves from CSV logs
generated by the `preprocess_and_train.py` PointNet training pipeline.

Each CSV log is expected to contain three columns: `epoch`, `loss`, and `acc`.

Usage Examples:
---------------
1. Automatically discover all train logs (train_log_exp*.csv) and plot both metrics:
   $ python visualize_training_logs.py

2. Plot both loss and accuracy for experiments 1, 2, and 3 only:
   $ python visualize_training_logs.py -e 1 2 3 --metric both

3. Plot only accuracy for experiment 2 and save to PNG:
   $ python visualize_training_logs.py --exp 2 --metric acc --save acc_exp2.png

Dependencies:
-------------
- pandas
- matplotlib

Install using:
$ pip install pandas matplotlib
"""

from __future__ import annotations

import argparse
import glob
import os
import re
from pathlib import Path
from typing import Dict, List

import pandas as pd
import matplotlib.pyplot as plt


# -----------------------------------------------------------------------------
# Command-Line Interface (CLI) Argument Parsing
# -----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """
    Define and parse command-line arguments for training log visualization.

    Returns:
        argparse.Namespace: Parsed arguments containing experiment numbers,
                            metric choice, save path, and root directory.
    """
    parser = argparse.ArgumentParser(
        description="Plot training loss and/or accuracy curves from PointNet logs",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "-e",
        "--exp",
        nargs="+",
        type=int,
        help="Experiment numbers to include (1‑6). If omitted, auto‑discover all.",
    )

    parser.add_argument(
        "--metric",
        choices=["loss", "acc", "both"],
        default="both",
        help="Which metric(s) to plot.",
    )

    parser.add_argument(
        "--save",
        type=str,
        default=None,
        help="Path to save the figure (PNG/PDF/SVG). If omitted, the plot is shown interactively.",
    )

    parser.add_argument(
        "--root",
        type=str,
        default=".",
        help="Project root to search for exp* folders.",
    )

    return parser.parse_args()



# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

CSV_PATTERN = re.compile(r"train_log.*exp(\d).*\.csv", re.IGNORECASE)


def discover_logs(root: Path, exps: List[int] | None) -> Dict[int, Path]:
    """
    Discover training log CSV files for selected experiments.

    Args:
        root (Path): The root directory to search (e.g., project base path).
        exps (List[int] | None): List of experiment numbers (1-6) to include.
                                 If None, discover all available logs.

    Returns:
        Dict[int, Path]: Mapping from experiment number → CSV file path.

    Notes:
        - Only searches depth-1 inside exp* directories under root.
        - If multiple logs are found for the same experiment, picks the first
          lexicographically.
        - Falls back to parent directory name to infer experiment number if filename pattern fails.
    """

    logs: Dict[int, Path] = {}

    # Construct glob patterns for specified experiments or default to all
    if exps:
        patterns = [f"exp{n}*/train_log*.csv" for n in exps]
    else:
        patterns = ["exp*/train_log*.csv"]

    for pattern in patterns:
        for csv_path in root.glob(pattern):
            # Try to extract experiment number from filename
            m = CSV_PATTERN.search(csv_path.name)
            exp_num = None
            if m:
                exp_num = int(m.group(1))
            else:
                # Fallback: derive from directory name like "exp1_baseline"
                par = csv_path.parent.name
                m2 = re.match(r"exp(\d)", par, re.IGNORECASE)
                if m2:
                    exp_num = int(m2.group(1))

            if exp_num is None:
                continue  # Cannot determine experiment number, skip

            if exps and exp_num not in exps:
                continue  # Skip experiments not in user-specified list

            # Only store the first valid CSV for each experiment
            logs.setdefault(exp_num, csv_path)

    if not logs:
        raise FileNotFoundError("No training logs found matching the criteria.")

    return dict(sorted(logs.items()))


# -----------------------------------------------------------------------------
# Plotting
# -----------------------------------------------------------------------------

def plot_logs(logs: Dict[int, Path], metric: str) -> plt.Figure:
    """
    Plot loss and/or accuracy curves from training logs.

    Args:
        logs (Dict[int, Path]): Mapping from experiment number → CSV path.
        metric (str): One of ["loss", "acc", "both"].

    Returns:
        matplotlib.pyplot.Figure: The resulting plot figure.
    """

    # Prepare appropriate subplots depending on metric
    if metric == "both":
        fig, (ax_loss, ax_acc) = plt.subplots(1, 2, figsize=(12, 5), sharex=True)
    else:
        fig, ax = plt.subplots(figsize=(6, 5))

    # Iterate over logs and plot values
    for exp_num, csv_path in logs.items():
        df = pd.read_csv(csv_path)
        epochs = df["epoch"]
        label_prefix = f"Exp{exp_num}"

        if metric in ("loss", "both"):
            ax_to_use = ax_loss if metric == "both" else ax
            ax_to_use.plot(epochs, df["loss"], label=f"{label_prefix} Loss")
            ax_to_use.set_ylabel("Loss")

        if metric in ("acc", "both"):
            ax_to_use = ax_acc if metric == "both" else ax
            ax_to_use.plot(epochs, df["acc"], label=f"{label_prefix} Acc")
            ax_to_use.set_ylabel("Accuracy")

    # Final formatting
    if metric == "both":
        ax_loss.set_xlabel("Epoch")
        ax_acc.set_xlabel("Epoch")
        ax_loss.set_title("Training Loss")
        ax_acc.set_title("Training Accuracy")
        ax_loss.legend()
        ax_acc.legend()
    else:
        ax.set_xlabel("Epoch")
        ax.set_title("Training " + ("Loss" if metric == "loss" else "Accuracy"))
        ax.legend()

    fig.tight_layout()
    return fig


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main() -> None:
    """
    Entry point of the script. Parses arguments, finds logs, plots curves,
    and either shows or saves the figure.
    """
    args = parse_args()
    root = Path(args.root).expanduser().resolve()

    try:
        logs = discover_logs(root, args.exp)
    except FileNotFoundError as e:
        print(e)
        return

    fig = plot_logs(logs, args.metric)

    if args.save:
        out_path = Path(args.save)
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        print(f"Figure saved to {out_path.resolve()}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
